[package]
name = "btcmbase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bincode = "1.3.3"
bitflags = "2.4.1"
getset = "0.1.2"
rand = "0.8.5"
serde = "1.0"
#serde_bytes = "0.11.14"
